name: CI - Playwright Tests

on:
  push:
    branches:
      - main   # You can change this to your target branch
  pull_request:
    branches:
      - main   # This triggers the CI pipeline on pull requests to `main`

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can specify the version you want

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Set up Groq API Key as a secret
      - name: Set up Groq API Key
        run: echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV

      # Run Playwright tests
      - name: Run Playwright Tests
        run: npx playwright test
